spring:
  profiles:
    active:
      dev
    group:
      local-env:
        - local
      dev-env:
        - dev
      prod-env:
        - prod
    include:
      - jwt

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB